INSERT INTO class VALUES (1, 'シューター', 'Shooters');
INSERT INTO class VALUES (2, 'ブラスター', 'Blaster');
INSERT INTO class VALUES (3, 'バースト', 'Burst-fire');
INSERT INTO class VALUES (4, 'ローラー', 'Rollers');
INSERT INTO class VALUES (5, 'フデ', 'Brushes');
INSERT INTO class VALUES (6, 'チャージャー', 'Chargers');
INSERT INTO class VALUES (7, 'スロッシャー', 'Sloshers');
INSERT INTO class VALUES (8, 'スピナー', 'Splatlings');

INSERT INTO sub VALUES (1, 'スプラッシュボム', 'Splat Bomb');
INSERT INTO sub VALUES (2, 'キューバンボム', 'Suction Bomb');
INSERT INTO sub VALUES (3, 'クイックボム', 'Burst Bomb');
INSERT INTO sub VALUES (4, 'チェイスボム', 'Seeker');
INSERT INTO sub VALUES (5, 'トラップ', 'Ink Mine');
INSERT INTO sub VALUES (6, 'ポイズンボール', 'Disruptor');
INSERT INTO sub VALUES (7, 'ポイントセンサー', 'Point Sensor');
INSERT INTO sub VALUES (8, 'スプラッシュシールド', 'Splash Wall');
INSERT INTO sub VALUES (9, 'スプリンクラー', 'Sprinkler');
INSERT INTO sub VALUES (10, 'ジャンプビーコン', 'Squid Beakon');

INSERT INTO special VALUES (1, 'ボムラッシュ', 'Bomb Rush');
INSERT INTO special VALUES (2, 'バリア', 'Bubbler');
INSERT INTO special VALUES (3, 'スーパーセンサー', 'Echolocator');
INSERT INTO special VALUES (4, 'トルネード', 'Inkstrike');
INSERT INTO special VALUES (5, 'スーパーショット', 'Inkzooka');
INSERT INTO special VALUES (6, 'メガホンレーザー', 'Killer Wail');
INSERT INTO special VALUES (7, 'ダイオウイカ', 'Kraken');

INSERT INTO weapon VALUES (1, 'ボールドマーカー', 'Sploosh-o-matic', 1, 10, 6);
INSERT INTO weapon VALUES (2, 'ボールドマーカーネオ', 'Neo Sploosh-o-matic', 1, 7, 7);
INSERT INTO weapon VALUES (3, 'ボールドマーカー７', 'Sploosh-o-matic 7', 1, 1, 5);
INSERT INTO weapon VALUES (4, 'わかばシューター', 'Splattershot Jr.', 1, 1, 2);
INSERT INTO weapon VALUES (5, 'もみじシューター', 'Custom Splattershot Jr.', 1, 6, 3);
INSERT INTO weapon VALUES (6, 'シャープマーカー', 'Splash-o-matic', 1, 2, 1);
INSERT INTO weapon VALUES (7, 'シャープマーカーネオ', 'Neo Splash-o-matic', 1, 3, 5);
INSERT INTO weapon VALUES (8, 'プロモデラーMG', 'Aerospray MG', 1, 4, 5);
INSERT INTO weapon VALUES (9, 'プロモデラーRG', 'Aerospray RG', 1, 5, 4);
INSERT INTO weapon VALUES (10, 'プロモデラーPG', 'Aerospray PG', 1, 3, 7);
INSERT INTO weapon VALUES (11, 'スプラシューター', 'Splattershot', 1, 3, 1);
INSERT INTO weapon VALUES (12, 'スプラシューターコラボ', 'Tentatek Splattershot', 1, 2, 5);
INSERT INTO weapon VALUES (13, 'スプラシューターワサビ', 'Wasabi Splattershot', 1, 1, 4);
INSERT INTO weapon VALUES (14, 'ヒーローシューターレプリカ', 'Hero Shot Replica', 1, 3, 1);
INSERT INTO weapon VALUES (15, 'オクタシューターレプリカ', 'Octo Shot Replica', 1, 2, 5);
INSERT INTO weapon VALUES (16, '.52ガロン', '.52 Gal', 1, 8, 6);
INSERT INTO weapon VALUES (17, '.52ガロンデコ', '.52 Gal Deco', 1, 4, 4);
INSERT INTO weapon VALUES (18, 'N-ZAP85', 'N-ZAP ''85', 1, 1, 3);
INSERT INTO weapon VALUES (19, 'N-ZAP89', 'N-ZAP ''89', 1, 9, 4);
INSERT INTO weapon VALUES (20, 'N-ZAP83', 'N-ZAP ''83', 1, 7, 7);
INSERT INTO weapon VALUES (21, 'デュアルスイーパー', 'Dual Squelcher', 1, 1, 3);
INSERT INTO weapon VALUES (22, 'デュアルスイーパーカスタム', 'Custom Dual Squelcher', 1, 10, 6);
INSERT INTO weapon VALUES (23, 'プライムシューター', 'Splattershot Pro', 1, 1, 4);
INSERT INTO weapon VALUES (24, 'プライムシューターコラボ', 'Forge Splattershot Pro', 1, 7, 5);
INSERT INTO weapon VALUES (25, 'プライムシューターベリー', 'Berry Splattershot Pro', 1, 2, 1);
INSERT INTO weapon VALUES (26, '.96ガロン', '.96 Gal', 1, 9, 3);
INSERT INTO weapon VALUES (27, '.96ガロンデコ', '.96 Gal Deco', 1, 8, 7);
INSERT INTO weapon VALUES (28, 'ジェットスイーパー', 'Jet Squelcher', 1, 8, 4);
INSERT INTO weapon VALUES (29, 'ジェットスイーパーカスタム', 'Custom Jet Squelcher', 1, 3, 7);
INSERT INTO weapon VALUES (30, 'ノヴァブラスター', 'Luna Blaster', 2, 5, 5);
INSERT INTO weapon VALUES (31, 'ノヴァブラスターネオ', 'Luna Blaster Neo', 2, 1, 1);
INSERT INTO weapon VALUES (32, 'ホットブラスター', 'Blaster', 2, 6, 6);
INSERT INTO weapon VALUES (33, 'ホットブラスターカスタム', 'Custom Blaster', 2, 7, 2);
INSERT INTO weapon VALUES (34, 'ロングブラスター', 'Range Blaster', 2, 8, 4);
INSERT INTO weapon VALUES (35, 'ロングブラスターカスタム', 'Custom Range Blaster', 2, 1, 7);
INSERT INTO weapon VALUES (36, 'ロングブラスターネクロ', 'Grim Range Blaster', 2, 3, 6);
INSERT INTO weapon VALUES (37, 'ラピッドブラスター', 'Rapid Blaster', 2, 5, 2);
INSERT INTO weapon VALUES (38, 'ラピッドブラスターデコ', 'Rapid Blaster Deco', 2, 2, 1);
INSERT INTO weapon VALUES (39, 'Rブラスターエリート', 'Rapid Blaster Pro', 2, 4, 5);
INSERT INTO weapon VALUES (40, 'Rブラスターエリートデコ', 'Rapid Blaster Pro Deco', 2, 6, 6);
INSERT INTO weapon VALUES (41, 'L3リールガン', 'L-3 Nozzlenose', 3, 6, 6);
INSERT INTO weapon VALUES (42, 'L3リールガンD', 'L-3 Nozzlenose D', 3, 3, 7);
INSERT INTO weapon VALUES (43, 'H3リールガン', 'H-3 Nozzlenose', 3, 2, 3);
INSERT INTO weapon VALUES (44, 'H3リールガンD', 'H-3 Nozzlenose D', 3, 7, 5);
INSERT INTO weapon VALUES (45, 'H3リールガンチェリー', 'Cherry H-3 Nozzlenose', 3, 8, 2);
INSERT INTO weapon VALUES (46, 'カーボンローラー', 'Carbon Roller', 4, 3, 5);
INSERT INTO weapon VALUES (47, 'カーボンローラーデコ', 'Carbon Roller Deco', 4, 4, 1);
INSERT INTO weapon VALUES (48, 'スプラローラー', 'Splat Roller', 4, 2, 6);
INSERT INTO weapon VALUES (49, 'スプラローラーコラボ', 'Krak-On Splat Roller', 4, 10, 7);
INSERT INTO weapon VALUES (50, 'スプラローラーコロコロ', 'CoroCoro Splat Roller', 4, 8, 5);
INSERT INTO weapon VALUES (51, 'ヒーローローラーレプリカ', 'Hero Roller Replica', 4, 2, 6);
INSERT INTO weapon VALUES (52, 'ダイナモローラー', 'Dynamo Roller', 4, 9, 3);
INSERT INTO weapon VALUES (53, 'ダイナモローラーテスラ', 'Gold Dynamo Roller', 4, 1, 4);
INSERT INTO weapon VALUES (54, 'ダイナモローラーバーンド', 'Tempered Dynamo Roller', 4, 4, 6);
INSERT INTO weapon VALUES (55, 'パブロ', 'Inkbrush', 5, 9, 4);
INSERT INTO weapon VALUES (56, 'パブロ・ヒュー', 'Inkbrush Nouveau', 5, 5, 2);
INSERT INTO weapon VALUES (57, 'パーマネント・パブロ', 'Permanent Inkbrush', 5, 1, 7);
INSERT INTO weapon VALUES (58, 'ホクサイ', 'Octobrush', 5, 10, 7);
INSERT INTO weapon VALUES (59, 'ホクサイ・ヒュー', 'Octobrush Nouveau', 5, 1, 5);
INSERT INTO weapon VALUES (60, 'スクイックリンα', 'Classic Squiffer', 6, 7, 2);
INSERT INTO weapon VALUES (61, 'スクイックリンβ', 'New Squiffer', 6, 5, 5);
INSERT INTO weapon VALUES (62, 'スクイックリンγ', 'Fresh Squiffer', 6, 2, 7);
INSERT INTO weapon VALUES (63, 'スプラチャージャー', 'Splat Charger', 6, 1, 1);
INSERT INTO weapon VALUES (64, 'スプラチャージャーワカメ', 'Kelp Splat Charger', 6, 9, 6);
INSERT INTO weapon VALUES (65, 'スプラチャージャーベントー', 'Bento Splat Charger', 6, 8, 6);
INSERT INTO weapon VALUES (66, 'ヒーローチャージャーレプリカ', 'Hero Charger Replica', 6, 1, 1);
INSERT INTO weapon VALUES (67, 'スプラスコープ', 'Splatterscope', 6, 1, 1);
INSERT INTO weapon VALUES (68, 'スプラスコープワカメ', 'Kelp Splatterscope', 6, 9, 6);
INSERT INTO weapon VALUES (69, 'スプラスコープベントー', 'Bento Splatterscope', 6, 8, 6);
INSERT INTO weapon VALUES (70, 'リッター3K', 'E-liter 3K', 6, 3, 3);
INSERT INTO weapon VALUES (71, 'リッター3Kカスタム', 'Custom E-liter 3K', 6, 10, 7);
INSERT INTO weapon VALUES (72, '3Kスコープ', 'E-liter 3K Scope', 6, 3, 3);
INSERT INTO weapon VALUES (73, '3Kスコープカスタム', 'Custom E-liter 3K Scope', 6, 10, 7);
INSERT INTO weapon VALUES (74, '14式竹筒銃・甲', 'Bamboozler 14 Mk I', 6, 8, 6);
INSERT INTO weapon VALUES (75, '14式竹筒銃・乙', 'Bamboozler 14 Mk II', 6, 6, 3);
INSERT INTO weapon VALUES (76, '14式竹筒銃・丙', 'Bamboozler 14 Mk III', 6, 3, 4);
INSERT INTO weapon VALUES (77, 'バケットスロッシャー', 'Slosher', 7, 3, 4);
INSERT INTO weapon VALUES (78, 'バケットスロッシャーデコ', 'Slosher Deco', 7, 8, 7);
INSERT INTO weapon VALUES (79, 'バケットスロッシャーソーダ', 'Soda Slosher', 7, 1, 4);
INSERT INTO weapon VALUES (80, 'ヒッセン', 'Tri-Slosher', 7, 6, 2);
INSERT INTO weapon VALUES (81, 'ヒッセン・ヒュー', 'Tri-Slosher Nouveau', 7, 4, 3);
INSERT INTO weapon VALUES (82, 'スクリュースロッシャー', 'Sloshing Machine', 7, 1, 1);
INSERT INTO weapon VALUES (83, 'スクリュースロッシャーネオ', 'Sloshing Machine Neo', 7, 7, 5);
INSERT INTO weapon VALUES (84, 'スプラスピナー', 'Mini Splatling', 8, 2, 5);
INSERT INTO weapon VALUES (85, 'スプラスピナーコラボ', 'Zink Mini Splatling', 8, 6, 2);
INSERT INTO weapon VALUES (86, 'スプラスピナーリペア', 'Refurbished Mini Splatling', 8, 3, 1);
INSERT INTO weapon VALUES (87, 'バレルスピナー', 'Heavy Splatling', 8, 8, 4);
INSERT INTO weapon VALUES (88, 'バレルスピナーデコ', 'Heavy Splatling Deco', 8, 7, 7);
INSERT INTO weapon VALUES (89, 'バレルスピナーリミックス', 'Heavy Splatling Remix', 8, 9, 6);
INSERT INTO weapon VALUES (90, 'ハイドラント', 'Hydra Splatling', 8, 1, 3);
INSERT INTO weapon VALUES (91, 'ハイドラントカスタム', 'Custom Hydra Splatling', 8, 9, 2);
